package avalanche.errors.model;

import android.support.annotation.VisibleForTesting;

/**
 * Exception for test crash
 */
public class TestCrashException extends RuntimeException {

    @VisibleForTesting
    static final String EXCEPTION_MESSAGE = "Test crash exception generated by SDK";

    public TestCrashException() {
        super(EXCEPTION_MESSAGE);
    }

    @SuppressWarnings("unused")
    @VisibleForTesting
    TestCrashException(String detailMessage) {
        throw new UnsupportedOperationException();
    }

    @SuppressWarnings("unused")
    @VisibleForTesting
    TestCrashException(String detailMessage, Throwable throwable) {
        throw new UnsupportedOperationException();
    }

    @SuppressWarnings("unused")
    @VisibleForTesting
    TestCrashException(Throwable throwable) {
        throw new UnsupportedOperationException();
    }
}
