stages:
- stage: PublishAzureMaven
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish Azure Maven
  dependsOn: stage
  jobs:
  - job: UploadArtifacts
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Build Artifacts
      inputs:
        artifactName: Release
        targetPath: '$(Agent.BuildDirectory)/Release'
    - task: MavenAuthenticate@0
      displayName: 'Maven Authenticate'
      inputs:
        artifactsFeeds: AppCenter
    - task: Bash@3
      displayName: Publish appcenter To AzureArtifacts
      inputs:
        targetType: 'inline'
        script: |
          VERSION=$(basename $(Agent.BuildDirectory)/Release/appcenter/appcenter/*/)
          ARTIFACTS_DIR="$(Agent.BuildDirectory)/Release/appcenter/appcenter/$VERSION"
          ARTIFACT_ID="appcenter"
          ARTIFACT_FILE_BASE="$ARTIFACTS_DIR/$ARTIFACT_ID-$VERSION"

          mvn deploy:deploy-file -DgeneratePom=false \
              -Durl=$(AZURE_REPO) \
              -Dfile=$ARTIFACT_FILE_BASE.aar \
              -Dfiles=$ARTIFACT_FILE_BASE.pom,$ARTIFACT_FILE_BASE-sources.jar,$ARTIFACT_FILE_BASE-javadoc.jar \
              -Dtypes=pom,jar,jar \
              -Dclassifiers=pom,sources,javadoc \
              -DgroupId=com.microsoft.appcenter \
              -DartifactId=$ARTIFACT_ID \
              -Dversion=$VERSION-${BUILD_SOURCEVERSION:0:7} \
              -DrepositoryId=AppCenter \
              -e
    - task: Bash@3
      displayName: Publish appcenter-analytics To AzureArtifacts
      inputs:
        targetType: 'inline'
        script: |
          VERSION=$(basename $(Agent.BuildDirectory)/Release/appcenter/appcenter-analytics/*/)
          ARTIFACTS_DIR="$(Agent.BuildDirectory)/Release/appcenter/appcenter-analytics/$VERSION"
          ARTIFACT_ID="appcenter-analytics"
          ARTIFACT_FILE_BASE="$ARTIFACTS_DIR/$ARTIFACT_ID-$VERSION"

          mvn deploy:deploy-file -DgeneratePom=false \
              -Durl=$(AZURE_REPO) \
              -Dfile=$ARTIFACT_FILE_BASE.aar \
              -Dfiles=$ARTIFACT_FILE_BASE.pom,$ARTIFACT_FILE_BASE-sources.jar,$ARTIFACT_FILE_BASE-javadoc.jar \
              -Dtypes=pom,jar,jar \
              -Dclassifiers=pom,sources,javadoc \
              -DgroupId=com.microsoft.appcenter \
              -DartifactId=$ARTIFACT_ID \
              -Dversion=$VERSION-${BUILD_SOURCEVERSION:0:7} \
              -DrepositoryId=AppCenter \
              -e
    - task: Bash@3
      displayName: Publish appcenter-crashes To AzureArtifacts
      inputs:
        targetType: 'inline'
        script: |
          VERSION=$(basename $(Agent.BuildDirectory)/Release/appcenter/appcenter-crashes/*/)
          ARTIFACTS_DIR="$(Agent.BuildDirectory)/Release/appcenter/appcenter-crashes/$VERSION"
          ARTIFACT_ID="appcenter-crashes"
          ARTIFACT_FILE_BASE="$ARTIFACTS_DIR/$ARTIFACT_ID-$VERSION"

          mvn deploy:deploy-file -DgeneratePom=false \
              -Durl=$(AZURE_REPO) \
              -Dfile=$ARTIFACT_FILE_BASE.aar \
              -Dfiles=$ARTIFACT_FILE_BASE.pom,$ARTIFACT_FILE_BASE-sources.jar,$ARTIFACT_FILE_BASE-javadoc.jar \
              -Dtypes=pom,jar,jar \
              -Dclassifiers=pom,sources,javadoc \
              -DgroupId=com.microsoft.appcenter \
              -DartifactId=$ARTIFACT_ID \
              -Dversion=$VERSION-${BUILD_SOURCEVERSION:0:7} \
              -DrepositoryId=AppCenter \
              -e

    - task: Bash@3
      displayName: Publish appcenter-distribute To AzureArtifacts
      inputs:
        targetType: 'inline'
        script: |
          VERSION=$(basename $(Agent.BuildDirectory)/Release/appcenter/appcenter-distribute/*/)
          ARTIFACTS_DIR="$(Agent.BuildDirectory)/Release/appcenter/appcenter-distribute/$VERSION"
          ARTIFACT_ID="appcenter-distribute"
          ARTIFACT_FILE_BASE="$ARTIFACTS_DIR/$ARTIFACT_ID-$VERSION"

          mvn deploy:deploy-file -DgeneratePom=false \
              -Durl=$(AZURE_REPO) \
              -Dfile=$ARTIFACT_FILE_BASE.aar \
              -Dfiles=$ARTIFACT_FILE_BASE.pom,$ARTIFACT_FILE_BASE-sources.jar,$ARTIFACT_FILE_BASE-javadoc.jar \
              -Dtypes=pom,jar,jar \
              -Dclassifiers=pom,sources,javadoc \
              -DgroupId=com.microsoft.appcenter \
              -DartifactId=$ARTIFACT_ID \
              -Dversion=$VERSION-${BUILD_SOURCEVERSION:0:7} \
              -DrepositoryId=AppCenter \
              -e