pr:
- master

pool:
  vmImage: macos-latest

variables:
- name: Codeql.Cadence
  value: 0

jobs:
- job:
  displayName: Build and CodeQL Sasquatch App
  steps:
  - checkout: self
    submodules: recursive
  - task: CodeQL3000Init@0
    displayName: CodeQL Initialize

  - task: Gradle@3
    displayName: Build Sasquatch App
    inputs:
      workingDirectory: apps
      tasks: assembleRelease
      publishJUnitResults: false

  - task: CodeQL3000Finalize@0
    displayName: CodeQL Finalize